### ISSUE TITLE
Valgrind reports invalid file descriptor -1 in syscall close

### ISSUE THREAD

**Issue by marcinwozniak0** [el-bart/but#5]
https://github.com/el-bart/but/blob/f73f2090dac79c5601408e998da57a049ad02c6d/src/But/System/TempFile.cpp#L18

Problem occurs during std::move on fd 

```
Descriptor(Descriptor&& other): desc_{ other.release() } { }  // now other.desc_ == -1

value_type release()
{
  const auto tmp = desc_;
  desc_ = -1;
  return tmp;
}
  
 ~Descriptor() { close(desc_); }   // valgrind reports   invalid file descriptor -1 in syscall close
 ```
 
 Fix proposal:
 ```
 ~Descriptor()
{
  if (-1 not_eq desc_)
  {   
     close(desc_);
  }   
}
 ```

**Comment by el-bart** [comment]
thanks for the report! :)

actually `Valgrind` is not right here - according to [POSIX it's ok to pass invalid descriptor](https://www.man7.org/linux/man-pages/man2/close.2.html) to `close()` - `EBADF` is returned in such a case.

however i still see a benefit in changing that, as we can avoid (pointless) syscall. silencing Valgrind also has an added value, as it limits false-positives. however since it is not a bug, i've applied this change to `master` only - see 0b4e2cb44a083d42111a729d103f1ce682678226 for details.

**Comment by el-bart** [comment]
btw: example program, that illustrates `close(-1)` behavior:
```cpp
#include <unistd.h>
#include <string.h>
#include <iostream>
#include <errno.h>

int main()
{
  auto ret = close(-1);
  std::cout << "ret == " << ret << std::endl;
  perror("close()");
}
```
prints:
```
ret == -1
close(): Bad file descriptor
```
